### ISSUE TITLE
cli: workflow deletion

### ISSUE THREAD

**Issue by dinosk** [reanahub/reana-client#192]
Should have option for soft/hard delete, delete all failed workflows.
Soft delete could be done through a new status `deleted`, hard delete could delete the row in the DB completely.

**Comment by dinosk** [comment]
The possible workflow states and the allowed transitions between them could be the following:
![workflow_states](https://user-images.githubusercontent.com/1566093/48203167-0a5ffe80-e367-11e8-82f1-04d154cc2e5a.png)

**Comment by tiborsimko** [comment]
Sounds good, except that the "restart" action may also apply to other states, notably `failed`.

**Comment by diegodelemos** [comment]
Regarding the `stop` state. Since by default it is going to be performed in a consistent way, but if invoked with `--force` consistency is not guaranteed, should we have to different states (i.e. `stopped`/`interrupted`) so an `stopped` workflow can be continued but an `interrupted` one can only be deleted?

**Comment by dinosk** [comment]
The PR group for this issue can be reviewed, not accounting for the user-facing cli flags.
Should be working according to the table in https://github.com/reanahub/reana-client/pull/195#discussion_r232629107.
For phrasing and options I would need some inspiration :)
