### ISSUE TITLE
cli: workflow stop

### ISSUE THREAD

**Issue by dinosk** [reanahub/reana-client#194]

**Comment by tiborsimko** [comment]
Use case scenario: a user submits some long-running workflow and realises a mistake.  It is wanted to `stop` it soon in order to liberate resources. The stop could be:

- (i) `--soft`, i.e. terminate the steps you are working on and do not proceed further; in this case the workflow run will end up in a consistent state;

- (ii) `--hard`, i.e. kill any running jobs the sooner the bettter; in this case the workflow may end up in a totally broken state.  

In the former use case, the user may be interesting in submitting corrected files and `continue`-ing the execution from some given step.  In the latter use case, the user may want to `delete` the workflow run and its workspace.

We can distinguish the above two possibilities via CLI options, even though we may implement only the latter option in this sprint.
