### ISSUE TITLE
cli: ls not working

### ISSUE THREAD

**Issue by dprelipcean** [reanahub/reana-client#312]
When running [this example](https://github.com/dprelipcean/reana-demo-cms-reco/tree/create_initial_structure), I encounter the following error after the workflow has finished (however unsuccessfully):

```console 
$ reana-client ls
Something went wrong while retrieving file list for workflow workflow.1:
resource '/cwl/docker_outdir/CMSSW_5_3_32/external/slc6_amd64_gcc472/objs-base' not found
```
I minikube sshed to manually find this file, and I got something strange imho:
```console
$ pwd
/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/18bb4784-86b2-4b27-ae86-b6be0154cca4/cwl/docker_outdir/CMSSW_5_3_32/external/slc6_amd64_gcc472
$ ls -la
total 0
drwxrwxr-x 2 docker root  0 Aug 12 08:01 .
drwxrwxr-x 3 docker root  0 Aug 12 08:01 ..
lrwxrwxrwx 1 docker root 72 Aug 12 08:01 objs-base -> /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/objs/slc6_amd64_gcc472
$ cd objs-base 
-bash: cd: objs-base: No such file or directory
```

Any ideas what this is about?

It might be related to this [issue](https://github.com/reanahub/reana-demo-cms-reco/issues/4).

**Comment by tiborsimko** [comment]
Happens for other workflows using CMSSW container, such as CMS dimuon spectrum example, that uses Serial workflow engine (not CWL) and that does not use "external" CVMFS:

```console
$ reana-client ls -w cms-dimuon-mass-spectrum.serial
Something went wrong while retrieving file list for workflow cms-dimuon-mass-spectrum.serial:
resource '/CMSSW_5_3_32/external/slc6_amd64_gcc472/objs-base' not found
```

**Comment by mvidalgarcia** [comment]
I think I found out what the problem is. The [list_directory_files()](https://github.com/reanahub/reana-workflow-controller/blob/d6c6588e3bb974f23c4b152b4070828605ae9880/reana_workflow_controller/utils.py#L48) function iterates through all the files in the workspace and (at least) one of them is a symlink that is pointing to a path that doesn't exist (maybe a path from the CMSSW container?). When performing [`fs_.getinfo()`](https://github.com/reanahub/reana-workflow-controller/blob/d6c6588e3bb974f23c4b152b4070828605ae9880/reana_workflow_controller/utils.py#L53) if fails as it can't find the file and the loop breaks so it can't list all the files nor find the result output file.

One solution could be identifying the symlinks and skip them. I've tried it and it works but I'm not sure if it's the best approach..
