### ISSUE TITLE
spec: validate specified docker images

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-client#382]
It has happened to have user workflows stuck with docker image related errors in production (see https://github.com/reanahub/reana-job-controller/issues/229 and https://github.com/reanahub/reana-job-controller/issues/3).

We could fix this by parsing and validating that all specified images have a correct name and other verifications such as if they can be pulled. This will avoid unnecessary waste of resources on the server-side.

**Comment by tiborsimko** [comment]
This is somewhat similar to validating whether image is not having any tag, or a moving tag such as `latest`, see https://github.com/reanahub/reana/issues/248#issuecomment-781963806

The `reana-client` could check for image existence.  Example: take roofit workflow, and instead of correct image `reanahub/reana-env-root6` people write `root5`, or instead of correct image tag `6.18.04` people write `6.18.44`. 

Some considerations:

- Ideally, a quick HEAD-like check should be attempted, e.g. reading image parameters without pulling it for real, since users may not have rights to run `docker`, and since pulling big 5 GB image would be too slow. 

- Perhaps using `singularity` or `would be OK though, since it can run in user space, and is available on many systems. Or `podman`.

- The wanted behaviour is that `reana-client validate` would signal an error or a very loud warning.

- Beware about private/public images, the workflow image may be living in a restricted repository, such as on GitLab, so the user executing `reana-client validate` may not necessarily have an access from the place it is run.  In this case, we could simply say that r-client could not verify image existence etc etc.

- Since this may take time, we should probably plug this under `validate` with a new CLI option, such as `validate --images`, leaving option for `validate --all` later.

**Comment by tiborsimko** [comment]
(P.S. Better call it `validate --environment`, to keep our inputs/workflow/environment/outputs nomenclature.

**Comment by mvidalgarcia** [comment]
Closed by https://github.com/reanahub/reana-client/pull/461
