### ISSUE TITLE
cli: option to show failed logs

### ISSUE THREAD

**Issue by alintulu** [reanahub/reana-client#415]
Add an option to only show failed job logs.

Example:

```
reana-client logs -w workflow --failed
```

Motivation: 

If a user runs a big workflow with hundreds of jobs it can be cumbersome to filter through all the job logs to find the subset that failed.

**Comment by tiborsimko** [comment]
We are already using filtering in other CLI commands, for example:

```
$ reana-client list --format status=finished
```

Instead of using just `--failed`, it would be good to design something fairly generic in a similar way.  This would allow getting logs of finished steps, failed steps, ongoing steps (once we have live streaming), etc.

We could go for the following CLI API:

```console
$ reana-client logs -w workflow --status failed
```

but what about making it even more generic to be able to filter on more than just status columns:

```console
$ reana-client logs -w workflow --filter status=failed --filter compute_backend=htcondorcern
```

which would apply two filters, one after another.

This could actually take care of:

```console
$ reana-client logs -w workflow --filter step=gendata
```

for which we currently have option `-s` that we could then remove.

This would take care of all the various filtering techniques in one upackage.

WDYT?

P.S. ... and we could perhaps touch upon `reana-client list --format` later so that we could do `reana-client --format=column1,column2 --filter column3=value4` that we had considered in the past.  Using `--format` or `--filter` kind of uniformly across all the various `reana-client` commands would provide nicely unified UX for the end user.

**Comment by alintulu** [comment]
I agree, this approach is more generic and hence better suited. I will look into implementing `--filter`.
