### ISSUE TITLE
cli: check disk usage information for CephFS shares

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#579]
We seem to represent incorrectly the total disk usage for Ceph volumes in CERN deployments. Perhaps due to unexpected block sizes (512 vs 1024).

Here is one test workflow run:

```
/var/reana/users/xxxx/workflows/yyyy
```

This is what the client reports:

```
$ reana-client du -s -w yyyy
SIZE      NAME
2705887   .

$ reana-client du -hs -w yyyy
SIZE       NAME
2.58 MiB   .
```

This is what `du` reports:

```
$ kubectl exec -i -t deployment/reana-server -c rest-api -- /bin/bash -c 'du -bs /var/reana/users/xxxx/workflows/yyyy'
2705887 /var/reana/users/xxxx/workflows/yyyy

$ kubectl exec -i -t deployment/reana-server -c rest-api -- /bin/bash -c 'du -hsc /var/reana/users/xxxx/workflows/yyyy'
1.3M    /var/reana/users/xxxx/workflows/yyyy
1.3M    total
```

**Comment by VMois** [comment]
Useful page about `du` command - https://www.gnu.org/software/coreutils/manual/html_node/du-invocation.html#du-invocation

Difference between `ls` and `du` - https://askubuntu.com/questions/1163839/what-is-difference-between-ls-lh-and-du-sh

**Comment by VMois** [comment]
My tests on dev environment.

File size usage in bytes:

```bash
kubectl exec -i -t reana-server-3333-aaaa -c rest-api -- /bin/bash -c "du -bs /var/reana/users/xxx/workflows/yyy"
520488  /var/reana/users/xxx/workflows/yyy
```

`-b` means `--block-size=1` **AND** `--apparent-size` (check [this page](https://www.gnu.org/software/coreutils/manual/html_node/du-invocation.html#du-invocation) for more details). `--apparent-size` prints file size, not file system usage.

Below is file system usage in kibibytes (1024):

```bash
kubectl exec -i -t reana-server-3333-aaaa -c rest-api -- /bin/bash -c "du -hsc /var/reana/users/xxx/workflows/yyy"
172K  /var/reana/users/xxx/workflows/yyy
172K  total
```

File system usage in bytes:

```bash
kubectl exec -i -t reana-server-3333-aaaa -c rest-api -- /bin/bash -c "du -sc --block-size=1 /var/reana/users/xxx/workflows/yyy"
176128  /var/reana/users/xxx/workflows/yyy
176128  total
```

*Note:* 176128 / 1024 = 172

File size usage with `-h`:

```bash
kubectl exec -i -t reana-server-3333-aaaa -c rest-api -- /bin/bash -c "du -hsc --apparent-size /var/reana/users/xxx/workflows/yyy"
509K  /var/reana/users/xxx/workflows/yyy
509K  total
```

As you can see difference comes from `--apparent-size`.

One interesting thing is that `ls -l` reports file size usage as:

```bash
kubectl exec -i -t reana-server-3333-aaaa -c rest-api -- /bin/bash -c "ls -l /var/reana/users/xxx/workflows/yyy"
total 1
drwxr-xr-x. 2 1000 1000   3585 Jan 27 09:40 code
drwxr-xr-x. 2 1000 root 169911 Jan 27 09:41 results
```

Which is equal to 169911 + 3585 = 173496 bytes, and not what we expect, around 520488 ([because `ls` calculates apparent sizes](https://askubuntu.com/questions/1163839/what-is-difference-between-ls-lh-and-du-sh)).

`ls -l --block-size=1` reports the same number as above.

**Comment by VMois** [comment]
The only solution I can see right now is to replace the usage of `-b` option in [`get_disk_usage` function](https://github.com/reanahub/reana-commons/blob/55458e2aba92db1bc1d7ced102b8870d0b5206ef/reana_commons/utils.py#L274) with `--block-size=1`. This will align disk usage output with `df` and `du` (in its original form) commands.

*Note 1:* this change shouldn't affect how workflow file sizes are displayed for users, but it might be confusing for them to see their used disk space be different from the total sum of their file sizes.

*Note 2:* we also need to remember that, for each file uploaded by a user, we update the quota with file size. So, in the end, file size might not reflect actual file space usage. This doesn't look like a big deal as we have periodic nightly quota updates.
