### ISSUE TITLE
can't remove the deleted recored

### ISSUE THREAD

**Issue by LittlePawer** [reanahub/reana-client#600]
Dear reana expert,

I found very annoying by seeing so many deleted entires everytime I list the workflows even after I use --include-all-runs and --include-workflow options when deleting them.

Is there any solution for that already?

Many thanks

**Comment by tiborsimko** [comment]
One thing you could do is to use the `--filter` option and list only those workflow runs that match statuses that interest you. 

For example, to see only "finished" workflow runs:

```console
$ reana-client list --filter status=finished 
```

or to see ones that are "queued" or "pending":

```console
$ reana-client list --filter status=queued --filter status=pending
``` 

Does this help your use case?

P.S. For the Web UI, see also https://github.com/reanahub/reana-ui/issues/218

**Comment by LittlePawer** [comment]
Hi @tiborsimko ,

Thanks for the reply. But this not only affect the way to look but also when you submit the same name workflows with something changed. 
I mean, usually it will assign a run number to it, but it will still count the deleted workflows which I don't think is necessary.

**Comment by tiborsimko** [comment]
I see your concern. The reason we perform soft-deletion of workflow runs by default is basically due to (i) recording full history and due to (ii) CPU quota accounting purposes. If a REANA cluster has "cpu" resource accounting feature turned on, then the REANA cluster admins can configure various runtime user limits, e.g. user U1 having a max of H1 hours runtime, user U2 having a max of H2 hours runtime, etc. The soft-deletion of workflows keeps the runtime information about past runs; the hard-deletion would remove those counters. If a REANA deployment does not use the quota accounting feature, and if having full history is not important (e.g. for personal deployments), then we could indeed allow hard-deletion of the workflows.

**Comment by LittlePawer** [comment]
Okay, I see. Many thanks for this detail explanation. Cureently I'm running jobs in CERN reana clusters, so I guess there is no way that this can be solved easily. Let's hope in the future we can have a perfect way out for both aims.
