### ISSUE TITLE
cwl: reana-cwl-runner incompatible with py2

### ISSUE THREAD

**Issue by anton-khodak** [reanahub/reana-client#66]

**Comment by diegodelemos** [comment]
We will have a conflict here since we are locked to Python 2.7 because of https://github.com/reanahub/reana-client/issues/17.

Even though it has been [fixed in `yadage-schemas`](https://github.com/diana-hep/yadage-schemas/issues/12) we are locked because we have to upgrade `yadage` version along with `yadage-schemas` (more info [here](https://github.com/reanahub/reana-client/pull/54)). Upgrading `yadage` might bring some headaches in `reana-workflow-engine-yadage` ...

**Comment by anton-khodak** [comment]
I will prioritize resolving it

**Comment by tiborsimko** [comment]
@anton-khodak The cwl-runner  is primarily necessary for the full CWL conformance test suite runner scenario, isn't it?  In this case it'll be good to change the milestone to `CWL-Full-Conformance`. If something is not fully required for the first three CWL examples to run  (such as the ROOT6 RooFit analysis demo), then let's rather use the later milestone (`CWL-Full-Conformance`). This will help us to prioritise the tasks necessary to run the first CWL examples (`CWL-First-Example`), which should be presumably easier to achieve than the full conformance. If this makes sense, perhaps you can go through the issues and recheck their triaging? 

- https://waffle.io/reanahub/reana?milestone=CWL-First-Example
- https://waffle.io/reanahub/reana?milestone=CWL-Full-Conformance

(Note that I have amended some milestones earlier today already.)

**Comment by tiborsimko** [comment]
@anton-khodak Can this be closed?  `reana-client` on Python-2.7 works well for me for the three CWL examples...

**Comment by anton-khodak** [comment]
Of course, this is resolved already
